config/routes.rb
Rails.application.routes.draw do

  root to: 'worker_bees#index'

  resources :worker_bees, only: [:index, :show, :update]
  resources :data_entry, only: [:edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comb.rb
class Comb < ApplicationRecord
  validates :name, :supervisor_id, :sweet_spot, presence: true

  has_many :staff_memberships,
    foreign_key: :comb_id,
    class_name: :CombStaffMembers

  has_many :worker_bees,
    through: :staff_memberships,
    source: :worker

  has_one :supervisor,
    foreign_key: :supervisor_id,
    class_name: :WorkerBee
  
end

app/models/comb_staff_member.rb
class CombStaffMember < ApplicationRecord
  validates :comb_id, :worker_id, presence: true

  belongs_to :comb,
    foreign_key: :comb_id,
    class_name: :Comb

  belongs_to :worker,
    foreign_key: :worker_id,
    class_name: :WorkerBee
  
end

app/models/data_entry.rb
class DataEntry < ApplicationRecord
  validates :worker_id, :date, :pollen_globs, :nectar, presence: true
  validates :advisement, numericality: { 
    only_integer: true, message: "has to be a number", allow_nil: true
  }

  belongs_to :bee,
    foreign_key: :worker_id,
    class_name: :WorkerBee
  
end

app/models/worker_bee.rb
class WorkerBee < ApplicationRecord
  validates :name, presence: true

  has_many :comb_memberships,
    foreign_key: :worker_id,
    class_name: :CombStaffMember
  
  has_many :combs,
    through: :comb_memberships,
    source: :comb

  has_many :supervised_combs,
    foreign_key: :supervisor_id,
    class_name: :Comb

  has_many :data_entries,
    foreign_key: :worker_id,
    class_name: :DataEntry
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/organize_worker_data.rb
module OrganizeWorkerData
  extend ActiveSupport::Concern
  include PercentageAccepted

  def self.organize(data)
    # variables for iteration
    data = data.reverse_order.limit(7)
    @curr_advisement = data.first.advisement
    percent_accepted = []
    @accepted = 0.0
    @rejected = 1.0
    
    # iterate each entry in data table and push into exchange gem variable
    data.each do |entry|
      # starter variables for accepted percentage logic
      if entry.advisement
        @curr_advisement = entry.advisement 
        @accepted = 0
        @rejected = 0
      end

      # call helper method and reassign variables
      results = PercentageAccepted.calculate(
        entry.nectar, @curr_advisement, @accepted, @rejected
      )
      percent_accepted.unshift(results[0].round()) # unshift because table goes from bottom-up (as per design docs)
      @accepted = results[1]
      @rejected = results[2]
    end

    percent_accepted
  end
  
end

app/controllers/concerns/percentage_accepted.rb
module PercentageAccepted
  extend ActiveSupport::Concern

  def self.calculate(nectar, advisement, accepted, rejected)
    if nectar == advisement
      accepted += 1.0
    end
    rejected += 1.0 # for mathy reasons rejected has to increase regardless

    percentage_accepted = accepted / rejected

    results = [percentage_accepted * 100.0, accepted, rejected]
  end
  
end

app/controllers/data_entry_controller.rb
class DataEntryController < ApplicationController
  
  def edit
    @entry = DataEntry.find_by(id: params[:id])
    render :edit
  end
  
  def update
    @entry = DataEntry.find_by(id: params[:id])
    if @entry.update(advisement: params[:advisement])
      redirect_to worker_bee_url(@entry.worker_id)
    else
      flash.now[:errors] = @entry.errors.full_messages
      render :edit
    end
  end
end

app/controllers/worker_bees_controller.rb
class WorkerBeesController < ApplicationController
  include OrganizeWorkerData

  def index
    @worker_bees = WorkerBee.all
    render :index
  end

  def show
    @comb_memberships = CombStaffMember.where(worker_id: params[:id]) # find all memberships
    @active_membership = @comb_memberships.order(:created_at).last # find active membership (last assigned comb)

    # get worker bee info for display
    @worker_bee = WorkerBee.find_by(id: params[:id])
    @comb = Comb.find_by(id: @active_membership.comb_id)
    @supervisor = WorkerBee.find_by(id: @comb.supervisor_id)

    @data = DataEntry.where(worker_id: params[:id]) # grab all data of worker bee
    
    # initialize data for charts
    gon.worker_name = @worker_bee.name
    gon.dates, gon.pg_values, gon.nectars = [], [], []
    
    @data = @data.order(:date).reverse_order
    @data.limit(7).each do |entry|
      gon.dates.unshift(entry.date)
      gon.pg_values.unshift(entry.pollen_globs)
      gon.nectars.unshift(entry.nectar / 100)
    end

    # calculate percentage accepted for tables
    @percent_accepted = OrganizeWorkerData.organize(@data)

    render :show
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/data_entry/_form.html.erb
  <a id="update-back-button" href="<%= worker_bee_url(entry.worker_id) %>">Back</a>

  <form id="update-advisement" action="<%= data_entry_url(entry) %>" method="POST">
    <% if flash[:errors] %>
        <p id="errors"><%= flash[:errors].join(", ") %></p>
    <% end %>
    <input type="hidden" name="_method" value="PATCH">

    <div id="value-spacer">
      <label id="form-value" for="advisement">New Advisement:</label>
    </div>
    <input id="new-advisement" type="text" name="advisement" value="<%= entry.advisement %>">
  <div id="update-background">
    <div id="submit-container">
      <input id="submit-update" type="submit">
    </div>
  </div>
  </form>

app/views/data_entry/edit.html.erb
<div id="update-container" class="animate__animated animate__fadeInDown">
  <h1 id="update-advisement-title">Change Advisement?</h1>
  <%= render "form", entry: @entry %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Where'sMyHoney</title>
    <%= csrf_meta_tags %>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"
    />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine|Inconsolata|Enriqueta|Roboto|Alata">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <%= Gon::Base.render_data %>
    <%= include_gon %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/worker_bees/index.html.erb
<div id="index-page" class="animate__animated animate__fadeIn">
  <h1 id="index-title">Very Track. Much Data</h1>
  <h3 id="list-title">Select a WorkerBee to display their metrics</h3>
  <div id="index-list">
    <% @worker_bees.each do |worker| %>
      <p id="index-list-item">
        <a id="list-worker-name" href="<%= worker_bee_url(worker.id) %>"><%= worker.name %></a>
      </p>
    <% end %>
  </div>
</div>

app/views/worker_bees/show.html.erb
<div id="show-container">
  <%# WorkerBee Bio Info %>
  <div id="bio">
    <h1 id="bio-title">
      <%= @worker_bee.name %>'s Identification Page
    </h1>
    <h3 id="bio-worker-id">
      WorkerBee ID: <strong id="bio-value"> 
        <%= @worker_bee.id %>
      </strong>
    </h3>
    <h3 id="bio-worker-comb">
      Assigned Comb: <strong id="bio-value"> 
        <%= @comb.name %> (Sweet Spot: <%= @comb.sweet_spot %>)
      </strong>
    </h3>
    <h3 id="bio-supervisor">
      Supervisor: <strong id="bio-value"> 
        <%= @supervisor.name %>
      </strong>
    </h3>
    <h3 id="bio-fav-food">
      Favorite Food: <strong id="bio-value"> 
        <%= @worker_bee.favorite_food %>
      </strong>
    </h3>
  </div>

  <%# ref for chart %>
  <div id="data-chart"></div>


  <%# table display %>
  <%# enhanced view table %>
  <div id="table-container">
  <button id="toggle-view">Toggle View</button>
    <table id="data-table">
      <tr id="data-table-titles">
        <th>ID</th>
        <th>ID-CombID</th>
        <th>Date</th>
        <th>PollenGlobs</th>
        <th>Nectar</th>
        <th>Advisement</th>
        <th>% Accepted</th>
      </tr>
      <% @data.each_with_index do |entry, idx| %>
        <tr id="data-table-values">
          <th><%= @worker_bee.id %></th>
          <th><%= @worker_bee.id %>-<%= @comb.id %></th>
          <th><%= entry.date %></th>
          <th><%= entry.pollen_globs %></th>
          <th><%= entry.nectar %></th>
          <% if entry.advisement %>
            <th><%= entry.advisement %></th>
          <% else %>
            <th>N/A</th>
          <% end %>
          <th><%= @percent_accepted[idx] %>%</th>
        </tr>
      <% end %>
    </table>

    <%# regular view table %>
    <table id="data-table-reg-blank">
      <tr id="data-table-titles-reg">
        <th>Date</th>
        <th>PollenGlobs</th>
        <th>Nectar</th>
        <th>Advisement</th>
        <th>Overrule</th>
      </tr>
      <% @data.each_with_index do |entry, idx| %>
        <tr id="data-table-values">
          <th><%= entry.date %></th>
          <th><%= entry.pollen_globs %></th>
          <th><%= entry.nectar %></th>
          <% if entry.advisement %>
            <th><%= entry.advisement %></th>
            <th>
              <button id="edit-advisement-button">
                <a id="edit-advisement-text" href="<%= edit_data_entry_url(entry) %>">Edit Advisement</a>
              </button>
            </th>
          <% else %>
            <th>N/A</th>
            <th></th>
          <% end %>
        </tr>
      <% end %>
    </table>
    <a id="bio-back-button" href="<%= worker_bees_url %>">Back</a>
  </div>
</div>


<%# table and chart javascript logic %>
<script>
  let toggle = document.getElementById("toggle-view")
  let switched = false

  toggle.addEventListener("click", function () {
    switched = !switched
  
    if (switched) {
      const mainTableShow = document.getElementById("data-table")
      const regTableBlank = document.getElementById("data-table-reg-blank")

      mainTableShow.setAttribute("id", "data-table-blank")
      regTableBlank.setAttribute("id", "data-table-reg")
    } else {
      const mainTableBlank = document.getElementById("data-table-blank")
      const regTableShow = document.getElementById("data-table-reg")

      mainTableBlank.setAttribute("id", "data-table")
      regTableShow.setAttribute("id", "data-table-reg-blank")
    }
  });

  document.addEventListener("DOMContentLoaded", function() {
    Highcharts.chart("data-chart", {
      chart: {
        renderTo: 'container'
      },
      title: {
        text: gon.worker_name + "'s Metrics"
      },
      xAxis: {
        categories: gon.dates
      },
      yAxis: {
        title: {
          text: 'Amount'
        }
      },
      series: [{
        type: 'column',
        name: 'Nectar (hundreds)',
        data: gon.nectars
      }, {
        type: 'line',
        name: 'Pollen Globs',
        data: gon.pg_values
      }]
    });
  });
</script>